const clientes = require('./clientesRoute')
const compra = require('./compraRoute')
const enderecos = require('./enderecosRoute')
const produtos = require('./produtosRoute')
const produtosCompra = require('./produtosCompraRoute')
const setores = require('./setoresRoute')
const unidadesMedida = require('./unidadesMedidaRoute')
const vendedores = require('./vendedoresRoute')
const produtosDaCompra = require('./produtosDaCompraRoute')

module.exports = (app) => {
    clientes(app)
    compra(app)
    enderecos(app)
    produtos(app)
    produtosCompra(app)
    setores(app)
    unidadesMedida(app)
    vendedores(app)
    produtosDaCompra(app)
} 